files:
  - source: /content/en/**
    translation: /content/%two_letters_code%/%original_file_name%
  - source: /content/en/lessons/**
    translation: /content/%two_letters_code%/lessons/%original_file_name%
  - source: /themes/nasin-lukin-pona/i18n/en.toml
    translation: /themes/nasin-lukin-pona/i18n/%two_letters_code%/es.toml
